import { GameDefinition } from "../../types";

export const COLORADO_GAMES: GameDefinition[] = [
  {
    game_id: "coloradolotto_co",
    state: "CO",
    displayName: "Colorado Lotto+",
    url: "https://www.lotteryusa.com/colorado/colorado-lotto-plus/",
    mainNumbers: 6,
    hasExtraBall: true,
    supportsCashValue: true,
    drawTimeET: "08:35 PM",
    daysOfWeek: [3, 6],
    table: "results_co",
  },
  {
    game_id: "cashfive_co",
    state: "CO",
    displayName: "Cash 5",
    url: "https://www.lotteryusa.com/colorado/cash-5/",
    mainNumbers: 5,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "07:35 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_co",
  },
  {
    game_id: "pick3midday_co",
    state: "CO",
    displayName: "Pick 3 Midday",
    url: "https://www.lotteryusa.com/colorado/pick-3-midday/",
    mainNumbers: 3,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "01:35 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_co",
  },
  {
    game_id: "pick3evening_co",
    state: "CO",
    displayName: "Pick 3 Evening",
    url: "https://www.lotteryusa.com/colorado/pick-3/",
    mainNumbers: 3,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "07:35 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_co",
  },
];
