import { GameDefinition } from "../../types";

export const KENTUCKY_GAMES: GameDefinition[] = [
  {
    game_id: "kylotto_ky",
    state: "KY",
    displayName: "Kentucky Lottery",
    url: "https://www.lotteryusa.com/kentucky/keno/",
    mainNumbers: 5,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "11:00 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_ky",
  },
  {
    game_id: "cash5_ky",
    state: "KY",
    displayName: "Cash Ball 225",
    url: "https://www.lotteryusa.com/kentucky/cash-ball/",
    mainNumbers: 4,
    hasExtraBall: true,
    supportsCashValue: false,
    drawTimeET: "11:00 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_ky",
  },
  {
    game_id: "pick3midday_ky",
    state: "KY",
    displayName: "Pick 3 Midday",
    url: "https://www.lotteryusa.com/kentucky/pick-3-midday/",
    mainNumbers: 3,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "12:29 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_ky",
  },
  {
    game_id: "pick3evening_ky",
    state: "KY",
    displayName: "Pick 3 Evening",
    url: "https://www.lotteryusa.com/kentucky/pick-3/",
    mainNumbers: 3,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "11:00 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_ky",
  },
  {
    game_id: "pick4midday_ky",
    state: "KY",
    displayName: "Pick 4 Midday",
    url: "https://www.lotteryusa.com/kentucky/pick-4-midday/",
    mainNumbers: 4,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "12:29 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_ky",
  },
  {
    game_id: "pick4evening_ky",
    state: "KY",
    displayName: "Pick 4 Evening",
    url: "https://www.lotteryusa.com/kentucky/pick-4/",
    mainNumbers: 4,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "11:00 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_ky",
  },
];
