import { GameDefinition } from "../../types";

export const MARYLAND_GAMES: GameDefinition[] = [
  {
    game_id: "mdlotto_md",
    state: "MD",
    displayName: "Lotto",
    url: "https://www.lotteryusa.com/maryland/lotto/",
    mainNumbers: 6,
    hasExtraBall: false,
    supportsCashValue: true,
    drawTimeET: "07:57 PM",
    daysOfWeek: [3, 6],
    table: "results_md",
  },
  {
    game_id: "mdbonus_md",
    state: "MD",
    displayName: "Bonus Match 5",
    url: "https://www.lotteryusa.com/maryland/bonus-match-5/",
    mainNumbers: 5,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "07:57 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_md",
  },
  {
    game_id: "pick3midday_md",
    state: "MD",
    displayName: "Pick 3 Midday",
    url: "https://www.lotteryusa.com/maryland/pick-3-midday/",
    mainNumbers: 3,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "12:28 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_md",
  },
  {
    game_id: "pick3evening_md",
    state: "MD",
    displayName: "Pick 3 Evening",
    url: "https://www.lotteryusa.com/maryland/pick-3/",
    mainNumbers: 3,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "07:57 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_md",
  },
  {
    game_id: "pick4midday_md",
    state: "MD",
    displayName: "Pick 4 Midday",
    url: "https://www.lotteryusa.com/maryland/pick-4-midday/",
    mainNumbers: 4,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "12:28 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_md",
  },
  {
    game_id: "pick4evening_md",
    state: "MD",
    displayName: "Pick 4 Evening",
    url: "https://www.lotteryusa.com/maryland/pick-4/",
    mainNumbers: 4,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "07:57 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_md",
  },
  {
    game_id: "pick5midday_md",
    state: "MD",
    displayName: "Pick 5 Midday",
    url: "https://www.lotteryusa.com/maryland/pick-5-midday/",
    mainNumbers: 5,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "12:28 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_md",
  },
  {
    game_id: "pick5evening_md",
    state: "MD",
    displayName: "Pick 5 Evening",
    url: "https://www.lotteryusa.com/maryland/pick-5/",
    mainNumbers: 5,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "07:57 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_md",
  },
];
