import { GameDefinition } from "../../types";

export const TENNESSEE_GAMES: GameDefinition[] = [
  {
    game_id: "tnlotto_tn",
    state: "TN",
    displayName: "Tennessee Cash",
    url: "https://www.lotteryusa.com/tennessee/tennessee-cash/",
    mainNumbers: 5,
    hasExtraBall: true,
    supportsCashValue: false,
    drawTimeET: "10:00 PM",
    daysOfWeek: [1, 3, 5],
    table: "results_tn",
  },
  {
    game_id: "cash3midday_tn",
    state: "TN",
    displayName: "Cash 3 Midday",
    url: "https://www.lotteryusa.com/tennessee/cash-3-midday/",
    mainNumbers: 3,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "01:29 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_tn",
  },
  {
    game_id: "cash3evening_tn",
    state: "TN",
    displayName: "Cash 3 Evening",
    url: "https://www.lotteryusa.com/tennessee/cash-3/",
    mainNumbers: 3,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "10:00 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_tn",
  },
  {
    game_id: "cash4midday_tn",
    state: "TN",
    displayName: "Cash 4 Midday",
    url: "https://www.lotteryusa.com/tennessee/cash-4-midday/",
    mainNumbers: 4,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "01:29 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_tn",
  },
  {
    game_id: "cash4evening_tn",
    state: "TN",
    displayName: "Cash 4 Evening",
    url: "https://www.lotteryusa.com/tennessee/cash-4/",
    mainNumbers: 4,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "10:00 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_tn",
  },
];
