import { GameDefinition } from "../../types";

export const TEXAS_GAMES: GameDefinition[] = [
  {
    game_id: "lottotexas_tx",
    state: "TX",
    displayName: "Lotto Texas",
    url: "https://www.lotteryusa.com/texas/lotto-texas/",
    mainNumbers: 6,
    hasExtraBall: false,
    supportsCashValue: true,
    drawTimeET: "11:12 PM",
    daysOfWeek: [3, 6],
    table: "results_tx",
  },
  {
    game_id: "texastwostep_tx",
    state: "TX",
    displayName: "Texas Two Step",
    url: "https://www.lotteryusa.com/texas/texas-two-step/",
    mainNumbers: 4,
    hasExtraBall: true,
    supportsCashValue: false,
    drawTimeET: "10:12 PM",
    daysOfWeek: [1, 4],
    table: "results_tx",
  },
  {
    game_id: "cashfive_tx",
    state: "TX",
    displayName: "Cash Five",
    url: "https://www.lotteryusa.com/texas/cash-five/",
    mainNumbers: 5,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "10:12 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_tx",
  },
  {
    game_id: "daily4morning_tx",
    state: "TX",
    displayName: "Daily 4 Morning",
    url: "https://www.lotteryusa.com/texas/daily-4-morning/",
    mainNumbers: 4,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "10:00 AM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_tx",
  },
  {
    game_id: "daily4day_tx",
    state: "TX",
    displayName: "Daily 4 Day",
    url: "https://www.lotteryusa.com/texas/daily-4-day/",
    mainNumbers: 4,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "12:27 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_tx",
  },
  {
    game_id: "daily4evening_tx",
    state: "TX",
    displayName: "Daily 4 Evening",
    url: "https://www.lotteryusa.com/texas/daily-4-evening/",
    mainNumbers: 4,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "06:27 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_tx",
  },
  {
    game_id: "daily4night_tx",
    state: "TX",
    displayName: "Daily 4 Night",
    url: "https://www.lotteryusa.com/texas/daily-4/",
    mainNumbers: 4,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "10:12 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_tx",
  },
  {
    game_id: "pick3morning_tx",
    state: "TX",
    displayName: "Pick 3 Morning",
    url: "https://www.lotteryusa.com/texas/pick-3-morning/",
    mainNumbers: 3,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "10:00 AM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_tx",
  },
  {
    game_id: "pick3day_tx",
    state: "TX",
    displayName: "Pick 3 Day",
    url: "https://www.lotteryusa.com/texas/pick-3-day/",
    mainNumbers: 3,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "12:27 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_tx",
  },
  {
    game_id: "pick3evening_tx",
    state: "TX",
    displayName: "Pick 3 Evening",
    url: "https://www.lotteryusa.com/texas/pick-3-evening/",
    mainNumbers: 3,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "06:27 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_tx",
  },
  {
    game_id: "pick3night_tx",
    state: "TX",
    displayName: "Pick 3 Night",
    url: "https://www.lotteryusa.com/texas/pick-3/",
    mainNumbers: 3,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "10:12 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_tx",
  },
  {
    game_id: "allornothingmorning_tx",
    state: "TX",
    displayName: "All or Nothing Morning",
    url: "https://www.lotteryusa.com/texas/all-or-nothing-morning/",
    mainNumbers: 12,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "10:00 AM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_tx",
  },
  {
    game_id: "allornothingday_tx",
    state: "TX",
    displayName: "All or Nothing Day",
    url: "https://www.lotteryusa.com/texas/all-or-nothing-day/",
    mainNumbers: 12,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "12:27 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_tx",
  },
  {
    game_id: "allornothingevening_tx",
    state: "TX",
    displayName: "All or Nothing Evening",
    url: "https://www.lotteryusa.com/texas/all-or-nothing-evening/",
    mainNumbers: 12,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "06:27 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_tx",
  },
  {
    game_id: "allornothingnight_tx",
    state: "TX",
    displayName: "All or Nothing Night",
    url: "https://www.lotteryusa.com/texas/all-or-nothing/",
    mainNumbers: 12,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "10:12 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_tx",
  },
];
