import { GameDefinition } from "../../types";

export const IDAHO_GAMES: GameDefinition[] = [
  {
    game_id: "idahocash_id",
    state: "ID",
    displayName: "Idaho Cash",
    url: "https://www.lotteryusa.com/idaho/idaho-cash/",
    mainNumbers: 5,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "08:00 PM",
    daysOfWeek: [1, 3, 5],
    table: "results_id",
  },
  {
    game_id: "pick4day_id",
    state: "ID",
    displayName: "Pick 4 Day",
    url: "https://www.lotteryusa.com/idaho/pick-4-day/",
    mainNumbers: 4,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "01:00 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_id",
  },
  {
    game_id: "pick4night_id",
    state: "ID",
    displayName: "Pick 4 Night",
    url: "https://www.lotteryusa.com/idaho/pick-4/",
    mainNumbers: 4,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "08:00 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_id",
  },
  {
    game_id: "pick3day_id",
    state: "ID",
    displayName: "Pick 3 Day",
    url: "https://www.lotteryusa.com/idaho/pick-3-day/",
    mainNumbers: 3,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "01:00 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_id",
  },
  {
    game_id: "pick3night_id",
    state: "ID",
    displayName: "Pick 3 Night",
    url: "https://www.lotteryusa.com/idaho/pick-3/",
    mainNumbers: 3,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "08:00 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_id",
  },
  // Multi-state → results_all
  {
    game_id: "lottoamerica",
    state: "ID",
    displayName: "Lotto America",
    url: "https://www.lotteryusa.com/idaho/lotto-america/",
    mainNumbers: 5,
    hasExtraBall: true,
    supportsCashValue: true,
    drawTimeET: "11:00 PM",
    daysOfWeek: [1, 3, 5],
  },
  {
    game_id: "luckyforlife",
    state: "ID",
    displayName: "Lucky for Life",
    url: "https://www.lotteryusa.com/idaho/lucky-for-life/",
    mainNumbers: 5,
    hasExtraBall: true,
    supportsCashValue: false,
    drawTimeET: "10:38 PM",
    daysOfWeek: [1, 4],
  },
];
