import { GameDefinition } from "../../types";

export const GEORGIA_GAMES: GameDefinition[] = [
  {
    game_id: "fantasia5_ga",
    state: "GA",
    displayName: "Fantasy 5",
    url: "https://www.lotteryusa.com/georgia/fantasy-5/",
    mainNumbers: 5,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "11:34 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_ga",
  },
  {
    game_id: "cash3midday_ga",
    state: "GA",
    displayName: "Cash 3 Midday",
    url: "https://www.lotteryusa.com/georgia/cash-3-midday/",
    mainNumbers: 3,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "12:29 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_ga",
  },
  {
    game_id: "cash3evening_ga",
    state: "GA",
    displayName: "Cash 3 Evening",
    url: "https://www.lotteryusa.com/georgia/cash-3/",
    mainNumbers: 3,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "11:34 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_ga",
  },
  {
    game_id: "cash4midday_ga",
    state: "GA",
    displayName: "Cash 4 Midday",
    url: "https://www.lotteryusa.com/georgia/cash-4-midday/",
    mainNumbers: 4,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "12:29 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_ga",
  },
  {
    game_id: "cash4evening_ga",
    state: "GA",
    displayName: "Cash 4 Evening",
    url: "https://www.lotteryusa.com/georgia/cash-4/",
    mainNumbers: 4,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "11:34 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_ga",
  },
  {
    game_id: "5card_ga",
    state: "GA",
    displayName: "5 Card Cash",
    url: "https://www.lotteryusa.com/georgia/5-card-cash/",
    mainNumbers: 5,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "11:34 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_ga",
  },
];
