import { GameDefinition } from "../../types";

export const FLORIDA_GAMES: GameDefinition[] = [
  // ── Multi-state ────────────────────────────────────────────
  {
    game_id: "megamillions_fl",
    state: "FL",
    displayName: "Mega Millions",
    url: "https://www.lotteryusa.com/florida/mega-millions/",
    mainNumbers: 5,
    hasExtraBall: true,
    supportsCashValue: true,
    drawTimeET: "11:00 PM",
    daysOfWeek: [2, 5],
    table: "results_fl",
  },

  {
    game_id: "powerball_fl",
    state: "FL",
    displayName: "Powerball",
    url: "https://www.lotteryusa.com/florida/powerball/",
    mainNumbers: 5,
    hasExtraBall: true,
    supportsCashValue: true,
    drawTimeET: "11:00 PM",
    daysOfWeek: [1, 4, 6],
    table: "results_fl",
  },

  {
    game_id: "powerballdp_fl",
    state: "FL",
    displayName: "Powerball Double Play",
    url: "https://www.lotteryusa.com/florida/powerball-double-play/",
    mainNumbers: 5,
    hasExtraBall: true,
    supportsCashValue: false,
    drawTimeET: "11:00 PM",
    daysOfWeek: [1, 4, 6],
    table: "results_fl",
  },

  // ── Florida exclusivos ─────────────────────────────────────
  {
    game_id: "floridalotto_fl",
    state: "FL",
    displayName: "Florida Lotto",
    url: "https://www.lotteryusa.com/florida/lotto/",
    mainNumbers: 6,
    hasExtraBall: false,
    supportsCashValue: true,
    drawTimeET: "11:15 PM",
    daysOfWeek: [3, 6],
    table: "results_fl",
  },

  {
    game_id: "jackpottripleplay_fl",
    state: "FL",
    displayName: "Jackpot Triple Play",
    url: "https://www.lotteryusa.com/florida/jackpot-triple-play/",
    mainNumbers: 6,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "11:15 PM",
    daysOfWeek: [1, 3, 6],
    table: "results_fl",
  },

  {
    game_id: "fantasy5midday_fl",
    state: "FL",
    displayName: "Fantasy 5 Midday",
    url: "https://www.lotteryusa.com/florida/fantasy-5-midday/",
    mainNumbers: 5,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "01:30 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_fl",
  },

  {
    game_id: "fantasy5evening_fl",
    state: "FL",
    displayName: "Fantasy 5 Evening",
    url: "https://www.lotteryusa.com/florida/fantasy-5/",
    mainNumbers: 5,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "09:45 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_fl",
  },

  // ── Pick games ─────────────────────────────────────────────
  {
    game_id: "pick2midday_fl",
    state: "FL",
    displayName: "Pick 2 Midday",
    url: "https://www.lotteryusa.com/florida/pick-2-midday/",
    mainNumbers: 2,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "01:30 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_fl",
  },

  {
    game_id: "pick2evening_fl",
    state: "FL",
    displayName: "Pick 2 Evening",
    url: "https://www.lotteryusa.com/florida/pick-2/",
    mainNumbers: 2,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "07:57 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_fl",
  },

  {
    game_id: "pick3midday_fl",
    state: "FL",
    displayName: "Pick 3 Midday",
    url: "https://www.lotteryusa.com/florida/midday-pick-3/",
    mainNumbers: 3,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "01:30 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_fl",
  },

  {
    game_id: "pick3evening_fl",
    state: "FL",
    displayName: "Pick 3 Evening",
    url: "https://www.lotteryusa.com/florida/pick-3/",
    mainNumbers: 3,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "07:57 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_fl",
  },

  {
    game_id: "pick4midday_fl",
    state: "FL",
    displayName: "Pick 4 Midday",
    url: "https://www.lotteryusa.com/florida/midday-pick-4/",
    mainNumbers: 4,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "01:30 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_fl",
  },

  {
    game_id: "pick4evening_fl",
    state: "FL",
    displayName: "Pick 4 Evening",
    url: "https://www.lotteryusa.com/florida/pick-4/",
    mainNumbers: 4,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "07:57 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_fl",
  },

  {
    game_id: "pick5midday_fl",
    state: "FL",
    displayName: "Pick 5 Midday",
    url: "https://www.lotteryusa.com/florida/pick-5-midday/",
    mainNumbers: 5,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "01:30 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_fl",
  },

  {
    game_id: "pick5evening_fl",
    state: "FL",
    displayName: "Pick 5 Evening",
    url: "https://www.lotteryusa.com/florida/pick-5/",
    mainNumbers: 5,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "07:57 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_fl",
  },
];
