import { GameDefinition } from "../../types";

// Jogos nacionais/multi-state → sem 'table' → salvam em results_all
const MULTISTATE_NY: GameDefinition[] = [
  {
    game_id: "megamillions",
    state: "NY",
    displayName: "Mega Millions",
    url: "https://www.lotteryusa.com/new-york/mega-millions/",
    mainNumbers: 5,
    hasExtraBall: true,
    supportsCashValue: true,
    drawTimeET: "11:00 PM",
    daysOfWeek: [2, 5],
  },
  {
    game_id: "powerball",
    state: "NY",
    displayName: "Powerball",
    url: "https://www.lotteryusa.com/new-york/powerball/",
    mainNumbers: 5,
    hasExtraBall: true,
    supportsCashValue: true,
    drawTimeET: "11:00 PM",
    daysOfWeek: [1, 4, 6],
  },
  {
    game_id: "powerballdp",
    state: "NY",
    displayName: "Powerball Double Play",
    url: "https://www.lotteryusa.com/new-york/powerball-double-play/",
    mainNumbers: 5,
    hasExtraBall: true,
    supportsCashValue: false,
    drawTimeET: "11:00 PM",
    daysOfWeek: [1, 4, 6],
  },
  {
    game_id: "millionaire4life",
    state: "NY",
    displayName: "Millionaire for Life",
    url: "https://www.lotteryusa.com/new-york/millionaire-for-life/",
    mainNumbers: 5,
    hasExtraBall: true,
    supportsCashValue: false,
    drawTimeET: "11:00 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
  },
];

// Jogos exclusivos NY → salvam em results_ny
const NY_GAMES: GameDefinition[] = [
  {
    game_id: "pick10_ny",
    state: "NY",
    displayName: "Pick 10",
    url: "https://www.lotteryusa.com/new-york/pick-10/",
    mainNumbers: 10,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "07:30 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_ny",
  },
  {
    game_id: "lotto_ny",
    state: "NY",
    displayName: "Lotto",
    url: "https://www.lotteryusa.com/new-york/lotto/",
    mainNumbers: 6,
    hasExtraBall: false,
    supportsCashValue: true,
    drawTimeET: "11:21 PM",
    daysOfWeek: [3, 6],
    table: "results_ny",
  },
  {
    game_id: "take5midday_ny",
    state: "NY",
    displayName: "Take 5 Midday",
    url: "https://www.lotteryusa.com/new-york/take-5-midday/",
    mainNumbers: 5,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "02:30 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_ny",
  },
  {
    game_id: "take5evening_ny",
    state: "NY",
    displayName: "Take 5 Evening",
    url: "https://www.lotteryusa.com/new-york/take-5/",
    mainNumbers: 5,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "10:30 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_ny",
  },
  {
    game_id: "win4midday_ny",
    state: "NY",
    displayName: "Win 4 Midday",
    url: "https://www.lotteryusa.com/new-york/win-4-midday/",
    mainNumbers: 4,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "02:30 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_ny",
  },
  {
    game_id: "win4evening_ny",
    state: "NY",
    displayName: "Win 4 Evening",
    url: "https://www.lotteryusa.com/new-york/win-4/",
    mainNumbers: 4,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "10:30 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_ny",
  },
  {
    game_id: "numbersmidday_ny",
    state: "NY",
    displayName: "Numbers Midday",
    url: "https://www.lotteryusa.com/new-york/numbers-midday/",
    mainNumbers: 3,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "02:30 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_ny",
  },
  {
    game_id: "numbersevening_ny",
    state: "NY",
    displayName: "Numbers Evening",
    url: "https://www.lotteryusa.com/new-york/numbers/",
    mainNumbers: 3,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "10:30 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_ny",
  },
];

export const NEW_YORK_GAMES: GameDefinition[] = [
  ...MULTISTATE_NY,
  ...NY_GAMES,
];
