import { GameDefinition } from "../../types";

export const NEW_YORK_GAMES: GameDefinition[] = [
  {
    game_id: "megamillions_ny",
    state: "NY",
    displayName: "Mega Millions",
    url: "https://www.lotteryusa.com/new-york/mega-millions/",
    mainNumbers: 5,
    hasExtraBall: true,
    supportsCashValue: true,
    drawTimeET: "11:00 PM",
    daysOfWeek: [2, 5],
  },

  {
    game_id: "powerball_ny",
    state: "NY",
    displayName: "Powerball",
    url: "https://www.lotteryusa.com/new-york/powerball/",
    mainNumbers: 5,
    hasExtraBall: true,
    supportsCashValue: true,
    drawTimeET: "11:00 PM",
    daysOfWeek: [1, 4, 6],
  },

  {
    game_id: "cash4life_ny",
    state: "NY",
    displayName: "Cash4Life",
    url: "https://www.lotteryusa.com/new-york/cash4life/",
    mainNumbers: 5,
    hasExtraBall: true,
    supportsCashValue: true,
    drawTimeET: "09:00 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
  },

  {
    game_id: "pick10_ny",
    state: "NY",
    displayName: "Pick 10",
    url: "https://www.lotteryusa.com/new-york/pick-10/",
    mainNumbers: 20,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "08:30 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
  },

  {
    game_id: "lotto_ny",
    state: "NY",
    displayName: "NY Lotto",
    url: "https://www.lotteryusa.com/new-york/lotto/",
    mainNumbers: 6,
    hasExtraBall: true,
    supportsCashValue: false,
    drawTimeET: "08:15 PM",
    daysOfWeek: [3, 6],
  },

  {
    game_id: "take5midday_ny",
    state: "NY",
    displayName: "Take 5 Midday",
    url: "https://www.lotteryusa.com/new-york/take-5-midday/",
    mainNumbers: 5,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "02:30 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
  },

  {
    game_id: "take5evening_ny",
    state: "NY",
    displayName: "Take 5 Evening",
    url: "https://www.lotteryusa.com/new-york/take-5/",
    mainNumbers: 5,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "08:30 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
  },

  {
    game_id: "win4midday_ny",
    state: "NY",
    displayName: "Win 4 Midday",
    url: "https://www.lotteryusa.com/new-york/midday-win-4/",
    mainNumbers: 4,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "02:30 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
  },

  {
    game_id: "win4evening_ny",
    state: "NY",
    displayName: "Win 4 Evening",
    url: "https://www.lotteryusa.com/new-york/win-4/",
    mainNumbers: 4,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "08:30 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
  },

  {
    game_id: "numbersmidday_ny",
    state: "NY",
    displayName: "Numbers Midday",
    url: "https://www.lotteryusa.com/new-york/midday-numbers/",
    mainNumbers: 3,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "02:30 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
  },

  {
    game_id: "numbersevening_ny",
    state: "NY",
    displayName: "Numbers Evening",
    url: "https://www.lotteryusa.com/new-york/numbers/",
    mainNumbers: 3,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "08:30 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
  },
];
