import { GameDefinition } from "../../types";

export const SOUTH_CAROLINA_GAMES: GameDefinition[] = [
  {
    game_id: "palmetto_sc",
    state: "SC",
    displayName: "Palmetto Cash 5",
    url: "https://www.lotteryusa.com/south-carolina/palmetto-cash-5/",
    mainNumbers: 5,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "11:59 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_sc",
  },
  {
    game_id: "pick3midday_sc",
    state: "SC",
    displayName: "Pick 3 Midday",
    url: "https://www.lotteryusa.com/south-carolina/pick-3-midday/",
    mainNumbers: 3,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "12:59 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_sc",
  },
  {
    game_id: "pick3evening_sc",
    state: "SC",
    displayName: "Pick 3 Evening",
    url: "https://www.lotteryusa.com/south-carolina/pick-3/",
    mainNumbers: 3,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "11:59 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_sc",
  },
  {
    game_id: "pick4midday_sc",
    state: "SC",
    displayName: "Pick 4 Midday",
    url: "https://www.lotteryusa.com/south-carolina/pick-4-midday/",
    mainNumbers: 4,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "12:59 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_sc",
  },
  {
    game_id: "pick4evening_sc",
    state: "SC",
    displayName: "Pick 4 Evening",
    url: "https://www.lotteryusa.com/south-carolina/pick-4/",
    mainNumbers: 4,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "11:59 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_sc",
  },
];
