import { GameDefinition } from "../../types";

export const NEW_HAMPSHIRE_GAMES: GameDefinition[] = [
  {
    game_id: "nhlotto_nh",
    state: "NH",
    displayName: "Gimme 5",
    url: "https://www.lotteryusa.com/new-hampshire/gimme-5/",
    mainNumbers: 5,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "07:59 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_nh",
  },
  {
    game_id: "pick3midday_nh",
    state: "NH",
    displayName: "Pick 3 Midday",
    url: "https://www.lotteryusa.com/new-hampshire/pick-3-midday/",
    mainNumbers: 3,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "01:00 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_nh",
  },
  {
    game_id: "pick3evening_nh",
    state: "NH",
    displayName: "Pick 3 Evening",
    url: "https://www.lotteryusa.com/new-hampshire/pick-3/",
    mainNumbers: 3,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "07:59 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_nh",
  },
  {
    game_id: "pick4midday_nh",
    state: "NH",
    displayName: "Pick 4 Midday",
    url: "https://www.lotteryusa.com/new-hampshire/pick-4-midday/",
    mainNumbers: 4,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "01:00 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_nh",
  },
  {
    game_id: "pick4evening_nh",
    state: "NH",
    displayName: "Pick 4 Evening",
    url: "https://www.lotteryusa.com/new-hampshire/pick-4/",
    mainNumbers: 4,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "07:59 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_nh",
  },
];
