import { GameDefinition } from "../../types";

export const VIRGINIA_GAMES: GameDefinition[] = [
  {
    game_id: "cash5_va",
    state: "VA",
    displayName: "Cash 5",
    url: "https://www.lotteryusa.com/virginia/cash-5/",
    mainNumbers: 5,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "11:00 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_va",
  },
  {
    game_id: "pick3midday_va",
    state: "VA",
    displayName: "Pick 3 Midday",
    url: "https://www.lotteryusa.com/virginia/pick-3-midday/",
    mainNumbers: 3,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "01:59 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_va",
  },
  {
    game_id: "pick3evening_va",
    state: "VA",
    displayName: "Pick 3 Evening",
    url: "https://www.lotteryusa.com/virginia/pick-3/",
    mainNumbers: 3,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "11:00 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_va",
  },
  {
    game_id: "pick4midday_va",
    state: "VA",
    displayName: "Pick 4 Midday",
    url: "https://www.lotteryusa.com/virginia/pick-4-midday/",
    mainNumbers: 4,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "01:59 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_va",
  },
  {
    game_id: "pick4evening_va",
    state: "VA",
    displayName: "Pick 4 Evening",
    url: "https://www.lotteryusa.com/virginia/pick-4/",
    mainNumbers: 4,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "11:00 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_va",
  },
  {
    game_id: "pick5midday_va",
    state: "VA",
    displayName: "Pick 5 Midday",
    url: "https://www.lotteryusa.com/virginia/pick-5-midday/",
    mainNumbers: 5,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "01:59 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_va",
  },
  {
    game_id: "pick5evening_va",
    state: "VA",
    displayName: "Pick 5 Evening",
    url: "https://www.lotteryusa.com/virginia/pick-5/",
    mainNumbers: 5,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "11:00 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_va",
  },
];
