import { GameDefinition } from "../../types";

export const ARKANSAS_GAMES: GameDefinition[] = [
  {
    game_id: "naturestatelotto_ar",
    state: "AR",
    displayName: "Natural State Jackpot",
    url: "https://www.lotteryusa.com/arkansas/natural-state-jackpot/",
    mainNumbers: 5,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "09:00 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_ar",
  },
  {
    game_id: "cash3midday_ar",
    state: "AR",
    displayName: "Cash 3 Midday",
    url: "https://www.lotteryusa.com/arkansas/cash-3-midday/",
    mainNumbers: 3,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "12:59 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_ar",
  },
  {
    game_id: "cash3evening_ar",
    state: "AR",
    displayName: "Cash 3 Evening",
    url: "https://www.lotteryusa.com/arkansas/cash-3/",
    mainNumbers: 3,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "06:59 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_ar",
  },
  {
    game_id: "cash4midday_ar",
    state: "AR",
    displayName: "Cash 4 Midday",
    url: "https://www.lotteryusa.com/arkansas/cash-4-midday/",
    mainNumbers: 4,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "12:59 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_ar",
  },
  {
    game_id: "cash4evening_ar",
    state: "AR",
    displayName: "Cash 4 Evening",
    url: "https://www.lotteryusa.com/arkansas/cash-4/",
    mainNumbers: 4,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "06:59 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_ar",
  },
];
