import { GameDefinition } from "../../types";

export const WISCONSIN_GAMES: GameDefinition[] = [
  {
    game_id: "wilotto_wi",
    state: "WI",
    displayName: "Badger 5",
    url: "https://www.lotteryusa.com/wisconsin/badger-5/",
    mainNumbers: 5,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "09:00 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_wi",
  },
  {
    game_id: "supercash_wi",
    state: "WI",
    displayName: "SuperCash!",
    url: "https://www.lotteryusa.com/wisconsin/supercash/",
    mainNumbers: 6,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "09:00 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_wi",
  },
  {
    game_id: "pick3midday_wi",
    state: "WI",
    displayName: "Pick 3 Midday",
    url: "https://www.lotteryusa.com/wisconsin/pick-3-midday/",
    mainNumbers: 3,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "01:00 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_wi",
  },
  {
    game_id: "pick3evening_wi",
    state: "WI",
    displayName: "Pick 3 Evening",
    url: "https://www.lotteryusa.com/wisconsin/pick-3/",
    mainNumbers: 3,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "09:00 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_wi",
  },
  {
    game_id: "pick4midday_wi",
    state: "WI",
    displayName: "Pick 4 Midday",
    url: "https://www.lotteryusa.com/wisconsin/pick-4-midday/",
    mainNumbers: 4,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "01:00 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_wi",
  },
  {
    game_id: "pick4evening_wi",
    state: "WI",
    displayName: "Pick 4 Evening",
    url: "https://www.lotteryusa.com/wisconsin/pick-4/",
    mainNumbers: 4,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "09:00 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_wi",
  },
];
