import { GameDefinition } from "../../types";

export const IOWA_GAMES: GameDefinition[] = [
  {
    game_id: "ialotto_ia",
    state: "IA",
    displayName: "Lotto America",
    url: "https://www.lotteryusa.com/iowa/lotto-america/",
    mainNumbers: 5,
    hasExtraBall: true,
    supportsCashValue: true,
    drawTimeET: "11:00 PM",
    daysOfWeek: [1, 3, 5],
  },
  {
    game_id: "iahot_ia",
    state: "IA",
    displayName: "Hot Lotto",
    url: "https://www.lotteryusa.com/iowa/pick-3/",
    mainNumbers: 3,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "09:00 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_ia",
  },
  {
    game_id: "pick3_ia",
    state: "IA",
    displayName: "Pick 3",
    url: "https://www.lotteryusa.com/iowa/pick-3/",
    mainNumbers: 3,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "09:00 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_ia",
  },
  {
    game_id: "pick4_ia",
    state: "IA",
    displayName: "Pick 4",
    url: "https://www.lotteryusa.com/iowa/pick-4/",
    mainNumbers: 4,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "09:00 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_ia",
  },
];
