import { GameDefinition } from "../../types";

export const WASHINGTON_GAMES: GameDefinition[] = [
  {
    game_id: "hit5_wa",
    state: "WA",
    displayName: "Hit 5",
    url: "https://www.lotteryusa.com/washington/hit-5/",
    mainNumbers: 5,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "08:00 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_wa",
  },
  {
    game_id: "match4_wa",
    state: "WA",
    displayName: "Match 4",
    url: "https://www.lotteryusa.com/washington/match-4/",
    mainNumbers: 4,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "08:00 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_wa",
  },
  {
    game_id: "dailygame_wa",
    state: "WA",
    displayName: "Daily Game",
    url: "https://www.lotteryusa.com/washington/daily-game/",
    mainNumbers: 3,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "08:00 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_wa",
  },
  {
    game_id: "lotto_wa",
    state: "WA",
    displayName: "Lotto",
    url: "https://www.lotteryusa.com/washington/lotto/",
    mainNumbers: 6,
    hasExtraBall: false,
    supportsCashValue: true,
    drawTimeET: "08:00 PM",
    daysOfWeek: [3, 6],
    table: "results_wa",
  },
];
