import { GameDefinition } from "../../types";

export const DELAWARE_GAMES: GameDefinition[] = [
  {
    game_id: "play3midday_de",
    state: "DE",
    displayName: "Play 3 Midday",
    url: "https://www.lotteryusa.com/delaware/play-3-midday/",
    mainNumbers: 3,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "01:30 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_de",
  },
  {
    game_id: "play3evening_de",
    state: "DE",
    displayName: "Play 3 Evening",
    url: "https://www.lotteryusa.com/delaware/play-3/",
    mainNumbers: 3,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "07:57 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_de",
  },
  {
    game_id: "play4midday_de",
    state: "DE",
    displayName: "Play 4 Midday",
    url: "https://www.lotteryusa.com/delaware/play-4-midday/",
    mainNumbers: 4,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "01:30 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_de",
  },
  {
    game_id: "play4evening_de",
    state: "DE",
    displayName: "Play 4 Evening",
    url: "https://www.lotteryusa.com/delaware/play-4/",
    mainNumbers: 4,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "07:57 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_de",
  },
  {
    game_id: "multiwindelaware_de",
    state: "DE",
    displayName: "Multi-Win Lotto",
    url: "https://www.lotteryusa.com/delaware/multi-win-lotto/",
    mainNumbers: 6,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "07:57 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_de",
  },
];
