import { GameDefinition } from "../../types";

export const NORTH_CAROLINA_GAMES: GameDefinition[] = [
  {
    game_id: "cashfive_nc",
    state: "NC",
    displayName: "Cash 5",
    url: "https://www.lotteryusa.com/north-carolina/cash-5/",
    mainNumbers: 5,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "11:22 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_nc",
  },
  {
    game_id: "pick3midday_nc",
    state: "NC",
    displayName: "Pick 3 Midday",
    url: "https://www.lotteryusa.com/north-carolina/pick-3-midday/",
    mainNumbers: 3,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "03:00 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_nc",
  },
  {
    game_id: "pick3evening_nc",
    state: "NC",
    displayName: "Pick 3 Evening",
    url: "https://www.lotteryusa.com/north-carolina/pick-3/",
    mainNumbers: 3,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "11:22 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_nc",
  },
  {
    game_id: "pick4midday_nc",
    state: "NC",
    displayName: "Pick 4 Midday",
    url: "https://www.lotteryusa.com/north-carolina/pick-4-midday/",
    mainNumbers: 4,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "03:00 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_nc",
  },
  {
    game_id: "pick4evening_nc",
    state: "NC",
    displayName: "Pick 4 Evening",
    url: "https://www.lotteryusa.com/north-carolina/pick-4/",
    mainNumbers: 4,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "11:22 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_nc",
  },
];
