import { GameDefinition } from "../../types";

export const MICHIGAN_GAMES: GameDefinition[] = [
  {
    game_id: "milotto_mi",
    state: "MI",
    displayName: "Lotto 47",
    url: "https://www.lotteryusa.com/michigan/lotto-47/",
    mainNumbers: 6,
    hasExtraBall: false,
    supportsCashValue: true,
    drawTimeET: "07:29 PM",
    daysOfWeek: [3, 6],
    table: "results_mi",
  },
  {
    game_id: "fantasy5_mi",
    state: "MI",
    displayName: "Fantasy 5",
    url: "https://www.lotteryusa.com/michigan/fantasy-5/",
    mainNumbers: 5,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "07:29 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_mi",
  },
  {
    game_id: "daily3midday_mi",
    state: "MI",
    displayName: "Daily 3 Midday",
    url: "https://www.lotteryusa.com/michigan/daily-3-midday/",
    mainNumbers: 3,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "12:59 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_mi",
  },
  {
    game_id: "daily3evening_mi",
    state: "MI",
    displayName: "Daily 3 Evening",
    url: "https://www.lotteryusa.com/michigan/daily-3/",
    mainNumbers: 3,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "07:29 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_mi",
  },
  {
    game_id: "daily4midday_mi",
    state: "MI",
    displayName: "Daily 4 Midday",
    url: "https://www.lotteryusa.com/michigan/daily-4-midday/",
    mainNumbers: 4,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "12:59 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_mi",
  },
  {
    game_id: "daily4evening_mi",
    state: "MI",
    displayName: "Daily 4 Evening",
    url: "https://www.lotteryusa.com/michigan/daily-4/",
    mainNumbers: 4,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "07:29 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_mi",
  },
];
