import { GameDefinition } from "../../types";

export const NEW_JERSEY_GAMES: GameDefinition[] = [
  {
    game_id: "njlotto_nj",
    state: "NJ",
    displayName: "Jersey Cash 5",
    url: "https://www.lotteryusa.com/new-jersey/jersey-cash-5/",
    mainNumbers: 5,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "10:57 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_nj",
  },
  {
    game_id: "pick3midday_nj",
    state: "NJ",
    displayName: "Pick 3 Midday",
    url: "https://www.lotteryusa.com/new-jersey/pick-3-midday/",
    mainNumbers: 3,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "01:00 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_nj",
  },
  {
    game_id: "pick3evening_nj",
    state: "NJ",
    displayName: "Pick 3 Evening",
    url: "https://www.lotteryusa.com/new-jersey/pick-3/",
    mainNumbers: 3,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "10:57 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_nj",
  },
  {
    game_id: "pick4midday_nj",
    state: "NJ",
    displayName: "Pick 4 Midday",
    url: "https://www.lotteryusa.com/new-jersey/pick-4-midday/",
    mainNumbers: 4,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "01:00 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_nj",
  },
  {
    game_id: "pick4evening_nj",
    state: "NJ",
    displayName: "Pick 4 Evening",
    url: "https://www.lotteryusa.com/new-jersey/pick-4/",
    mainNumbers: 4,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "10:57 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_nj",
  },
  {
    game_id: "pick6_nj",
    state: "NJ",
    displayName: "Pick 6",
    url: "https://www.lotteryusa.com/new-jersey/pick-6/",
    mainNumbers: 6,
    hasExtraBall: false,
    supportsCashValue: true,
    drawTimeET: "10:57 PM",
    daysOfWeek: [1, 3, 6],
    table: "results_nj",
  },
];
