import { GameDefinition } from "../../types";

export const CALIFORNIA_GAMES: GameDefinition[] = [
  {
    game_id: "superlottoplus_ca",
    state: "CA",
    displayName: "SuperLotto Plus",
    url: "https://www.lotteryusa.com/california/super-lotto-plus/",
    mainNumbers: 5,
    hasExtraBall: true,
    supportsCashValue: true,
    drawTimeET: "08:00 PM",
    daysOfWeek: [3, 6],
    table: "results_ca",
  },
  {
    game_id: "fantasy5_ca",
    state: "CA",
    displayName: "Fantasy 5",
    url: "https://www.lotteryusa.com/california/fantasy-5/",
    mainNumbers: 5,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "06:30 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_ca",
  },
  {
    game_id: "daily4_ca",
    state: "CA",
    displayName: "Daily 4",
    url: "https://www.lotteryusa.com/california/daily-4/",
    mainNumbers: 4,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "06:30 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_ca",
  },
  {
    game_id: "daily3midday_ca",
    state: "CA",
    displayName: "Daily 3 Midday",
    url: "https://www.lotteryusa.com/california/daily-3-midday/",
    mainNumbers: 3,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "01:00 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_ca",
  },
  {
    game_id: "daily3evening_ca",
    state: "CA",
    displayName: "Daily 3 Evening",
    url: "https://www.lotteryusa.com/california/daily-3/",
    mainNumbers: 3,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "06:30 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_ca",
  },
  {
    game_id: "dailyderby_ca",
    state: "CA",
    displayName: "Daily Derby",
    url: "https://www.lotteryusa.com/california/daily-derby/",
    mainNumbers: 3,
    hasExtraBall: true,
    supportsCashValue: false,
    drawTimeET: "06:30 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_ca",
  },
];
