import { GameDefinition } from "../../types";

export const CONNECTICUT_GAMES: GameDefinition[] = [
  {
    game_id: "classclotto_ct",
    state: "CT",
    displayName: "Classic Lotto",
    url: "https://www.lotteryusa.com/connecticut/lotto/",
    mainNumbers: 6,
    hasExtraBall: false,
    supportsCashValue: true,
    drawTimeET: "10:38 PM",
    daysOfWeek: [1, 4],
    table: "results_ct",
  },
  {
    game_id: "play3midday_ct",
    state: "CT",
    displayName: "Play 3 Midday",
    url: "https://www.lotteryusa.com/connecticut/play-3-midday/",
    mainNumbers: 3,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "01:57 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_ct",
  },
  {
    game_id: "play3evening_ct",
    state: "CT",
    displayName: "Play 3 Evening",
    url: "https://www.lotteryusa.com/connecticut/play-3/",
    mainNumbers: 3,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "10:29 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_ct",
  },
  {
    game_id: "play4midday_ct",
    state: "CT",
    displayName: "Play 4 Midday",
    url: "https://www.lotteryusa.com/connecticut/play-4-midday/",
    mainNumbers: 4,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "01:57 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_ct",
  },
  {
    game_id: "play4evening_ct",
    state: "CT",
    displayName: "Play 4 Evening",
    url: "https://www.lotteryusa.com/connecticut/play-4/",
    mainNumbers: 4,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "10:29 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_ct",
  },
];
