import { GameDefinition } from "../../types";

export const LOUISIANA_GAMES: GameDefinition[] = [
  {
    game_id: "louisianalotto_la",
    state: "LA",
    displayName: "Lotto",
    url: "https://www.lotteryusa.com/louisiana/lotto/",
    mainNumbers: 6,
    hasExtraBall: false,
    supportsCashValue: true,
    drawTimeET: "10:00 PM",
    daysOfWeek: [3, 6],
    table: "results_la",
  },
  {
    game_id: "easyfive_la",
    state: "LA",
    displayName: "Easy 5",
    url: "https://www.lotteryusa.com/louisiana/easy-5/",
    mainNumbers: 5,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "10:00 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_la",
  },
  {
    game_id: "pick3_la",
    state: "LA",
    displayName: "Pick 3",
    url: "https://www.lotteryusa.com/louisiana/pick-3/",
    mainNumbers: 3,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "09:00 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_la",
  },
  {
    game_id: "pick4_la",
    state: "LA",
    displayName: "Pick 4",
    url: "https://www.lotteryusa.com/louisiana/pick-4/",
    mainNumbers: 4,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "09:00 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_la",
  },
  {
    game_id: "pick5_la",
    state: "LA",
    displayName: "Pick 5",
    url: "https://www.lotteryusa.com/louisiana/pick-5/",
    mainNumbers: 5,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "09:00 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_la",
  },
];
