import { GameDefinition } from "../../types";

export const DISTRICT_OF_COLUMBIA_GAMES: GameDefinition[] = [
  {
    game_id: "dclotto_dc",
    state: "DC",
    displayName: "DC-5",
    url: "https://www.lotteryusa.com/washington-dc/dc-5/",
    mainNumbers: 5,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "09:00 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_dc",
  },
  {
    game_id: "pick3midday_dc",
    state: "DC",
    displayName: "Pick 3 Midday",
    url: "https://www.lotteryusa.com/washington-dc/pick-3-midday/",
    mainNumbers: 3,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "01:30 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_dc",
  },
  {
    game_id: "pick3evening_dc",
    state: "DC",
    displayName: "Pick 3 Evening",
    url: "https://www.lotteryusa.com/washington-dc/pick-3/",
    mainNumbers: 3,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "09:00 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_dc",
  },
  {
    game_id: "pick4midday_dc",
    state: "DC",
    displayName: "Pick 4 Midday",
    url: "https://www.lotteryusa.com/washington-dc/pick-4-midday/",
    mainNumbers: 4,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "01:30 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_dc",
  },
  {
    game_id: "pick4evening_dc",
    state: "DC",
    displayName: "Pick 4 Evening",
    url: "https://www.lotteryusa.com/washington-dc/pick-4/",
    mainNumbers: 4,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "09:00 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_dc",
  },
];
