import { GameDefinition } from "../../types";

export const MISSOURI_GAMES: GameDefinition[] = [
  {
    game_id: "molotto_mo",
    state: "MO",
    displayName: "Lotto",
    url: "https://www.lotteryusa.com/missouri/lotto/",
    mainNumbers: 6,
    hasExtraBall: false,
    supportsCashValue: true,
    drawTimeET: "09:00 PM",
    daysOfWeek: [3, 6],
    table: "results_mo",
  },
  {
    game_id: "showmecash_mo",
    state: "MO",
    displayName: "Show Me Cash",
    url: "https://www.lotteryusa.com/missouri/show-me-cash/",
    mainNumbers: 5,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "09:00 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_mo",
  },
  {
    game_id: "pick3midday_mo",
    state: "MO",
    displayName: "Pick 3 Midday",
    url: "https://www.lotteryusa.com/missouri/pick-3-midday/",
    mainNumbers: 3,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "01:00 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_mo",
  },
  {
    game_id: "pick3evening_mo",
    state: "MO",
    displayName: "Pick 3 Evening",
    url: "https://www.lotteryusa.com/missouri/pick-3/",
    mainNumbers: 3,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "09:00 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_mo",
  },
  {
    game_id: "pick4midday_mo",
    state: "MO",
    displayName: "Pick 4 Midday",
    url: "https://www.lotteryusa.com/missouri/pick-4-midday/",
    mainNumbers: 4,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "01:00 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_mo",
  },
  {
    game_id: "pick4evening_mo",
    state: "MO",
    displayName: "Pick 4 Evening",
    url: "https://www.lotteryusa.com/missouri/pick-4/",
    mainNumbers: 4,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "09:00 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_mo",
  },
];
