import { GameDefinition } from "../../types";

export const INDIANA_GAMES: GameDefinition[] = [
  {
    game_id: "hoosierhoopla_in",
    state: "IN",
    displayName: "Hoosier Lotto",
    url: "https://www.lotteryusa.com/indiana/hoosier-lotto/",
    mainNumbers: 6,
    hasExtraBall: false,
    supportsCashValue: true,
    drawTimeET: "11:00 PM",
    daysOfWeek: [3, 6],
    table: "results_in",
  },
  {
    game_id: "cash5_in",
    state: "IN",
    displayName: "Cash 5",
    url: "https://www.lotteryusa.com/indiana/cash-5/",
    mainNumbers: 5,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "11:00 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_in",
  },
  {
    game_id: "daily3midday_in",
    state: "IN",
    displayName: "Daily 3 Midday",
    url: "https://www.lotteryusa.com/indiana/daily-3-midday/",
    mainNumbers: 3,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "01:20 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_in",
  },
  {
    game_id: "daily3evening_in",
    state: "IN",
    displayName: "Daily 3 Evening",
    url: "https://www.lotteryusa.com/indiana/daily-3/",
    mainNumbers: 3,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "11:00 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_in",
  },
  {
    game_id: "daily4midday_in",
    state: "IN",
    displayName: "Daily 4 Midday",
    url: "https://www.lotteryusa.com/indiana/daily-4-midday/",
    mainNumbers: 4,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "01:20 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_in",
  },
  {
    game_id: "daily4evening_in",
    state: "IN",
    displayName: "Daily 4 Evening",
    url: "https://www.lotteryusa.com/indiana/daily-4/",
    mainNumbers: 4,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "11:00 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_in",
  },
];
