import { GameDefinition } from "../../types";

export const ILLINOIS_GAMES: GameDefinition[] = [
  {
    game_id: "illinoislotto_il",
    state: "IL",
    displayName: "Lotto",
    url: "https://www.lotteryusa.com/illinois/lotto/",
    mainNumbers: 6,
    hasExtraBall: false,
    supportsCashValue: true,
    drawTimeET: "09:22 PM",
    daysOfWeek: [1, 3, 6],
    table: "results_il",
  },
  {
    game_id: "littlelotto_il",
    state: "IL",
    displayName: "Little Lotto",
    url: "https://www.lotteryusa.com/illinois/little-lotto/",
    mainNumbers: 5,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "09:22 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_il",
  },
  {
    game_id: "pick3midday_il",
    state: "IL",
    displayName: "Pick 3 Midday",
    url: "https://www.lotteryusa.com/illinois/pick-3-midday/",
    mainNumbers: 3,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "12:40 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_il",
  },
  {
    game_id: "pick3evening_il",
    state: "IL",
    displayName: "Pick 3 Evening",
    url: "https://www.lotteryusa.com/illinois/pick-3/",
    mainNumbers: 3,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "09:22 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_il",
  },
  {
    game_id: "pick4midday_il",
    state: "IL",
    displayName: "Pick 4 Midday",
    url: "https://www.lotteryusa.com/illinois/pick-4-midday/",
    mainNumbers: 4,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "12:40 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_il",
  },
  {
    game_id: "pick4evening_il",
    state: "IL",
    displayName: "Pick 4 Evening",
    url: "https://www.lotteryusa.com/illinois/pick-4/",
    mainNumbers: 4,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "09:22 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_il",
  },
];
