import { GameDefinition } from "../../types";

export const PENNSYLVANIA_GAMES: GameDefinition[] = [
  {
    game_id: "pick2midday_pa",
    state: "PA",
    displayName: "Pick 2 Midday",
    url: "https://www.lotteryusa.com/pennsylvania/midday-pick-2/",
    mainNumbers: 2,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "01:35 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
  },

  {
    game_id: "pick2evening_pa",
    state: "PA",
    displayName: "Pick 2 Evening",
    url: "https://www.lotteryusa.com/pennsylvania/pick-2/",
    mainNumbers: 2,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "06:59 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
  },

  {
    game_id: "pick3midday_pa",
    state: "PA",
    displayName: "Pick 3 Midday",
    url: "https://www.lotteryusa.com/pennsylvania/midday-pick-3/",
    mainNumbers: 3,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "01:35 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
  },

  {
    game_id: "pick3evening_pa",
    state: "PA",
    displayName: "Pick 3 Evening",
    url: "https://www.lotteryusa.com/pennsylvania/pick-3/",
    mainNumbers: 3,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "06:59 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
  },

  {
    game_id: "pick4midday_pa",
    state: "PA",
    displayName: "Pick 4 Midday",
    url: "https://www.lotteryusa.com/pennsylvania/midday-pick-4/",
    mainNumbers: 4,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "01:35 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
  },

  {
    game_id: "pick4evening_pa",
    state: "PA",
    displayName: "Pick 4 Evening",
    url: "https://www.lotteryusa.com/pennsylvania/pick-4/",
    mainNumbers: 4,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "06:59 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
  },

  {
    game_id: "pick5midday_pa",
    state: "PA",
    displayName: "Pick 5 Midday",
    url: "https://www.lotteryusa.com/pennsylvania/midday-pick-5/",
    mainNumbers: 5,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "01:35 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
  },

  {
    game_id: "pick5evening_pa",
    state: "PA",
    displayName: "Pick 5 Evening",
    url: "https://www.lotteryusa.com/pennsylvania/pick-5/",
    mainNumbers: 5,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "06:59 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
  },

  {
    game_id: "treasurehunt_pa",
    state: "PA",
    displayName: "Treasure Hunt",
    url: "https://www.lotteryusa.com/pennsylvania/treasure-hunt/",
    mainNumbers: 5,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "01:35 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
  },

  {
    game_id: "cash5_pa",
    state: "PA",
    displayName: "Cash 5",
    url: "https://www.lotteryusa.com/pennsylvania/cash-5/",
    mainNumbers: 5,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "06:59 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
  },

  {
    game_id: "match6_pa",
    state: "PA",
    displayName: "Match 6",
    url: "https://www.lotteryusa.com/pennsylvania/match-6/",
    mainNumbers: 6,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "06:59 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
  },

  {
    game_id: "cash4life_pa",
    state: "PA",
    displayName: "Cash4Life",
    url: "https://www.lotteryusa.com/pennsylvania/cash4life/",
    mainNumbers: 5,
    hasExtraBall: true,
    supportsCashValue: true,
    drawTimeET: "09:00 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
  },

  {
    game_id: "megamillions_pa",
    state: "PA",
    displayName: "Mega Millions",
    url: "https://www.lotteryusa.com/pennsylvania/mega-millions/",
    mainNumbers: 5,
    hasExtraBall: true,
    supportsCashValue: true,
    drawTimeET: "11:00 PM",
    daysOfWeek: [2, 5],
  },

  {
    game_id: "powerball_pa",
    state: "PA",
    displayName: "Powerball",
    url: "https://www.lotteryusa.com/pennsylvania/powerball/",
    mainNumbers: 5,
    hasExtraBall: true,
    supportsCashValue: true,
    drawTimeET: "10:59 PM",
    daysOfWeek: [1, 3, 6],
  },
];
