import { GameDefinition } from "../../types";

export const MAINE_GAMES: GameDefinition[] = [
  {
    game_id: "meganumber_me",
    state: "ME",
    displayName: "Megabucks Doubler",
    url: "https://www.lotteryusa.com/maine/megabucks-doubler/",
    mainNumbers: 6,
    hasExtraBall: false,
    supportsCashValue: true,
    drawTimeET: "07:59 PM",
    daysOfWeek: [3, 6],
    table: "results_me",
  },
  {
    game_id: "pick3midday_me",
    state: "ME",
    displayName: "Pick 3 Midday",
    url: "https://www.lotteryusa.com/maine/pick-3-midday/",
    mainNumbers: 3,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "01:00 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_me",
  },
  {
    game_id: "pick3evening_me",
    state: "ME",
    displayName: "Pick 3 Evening",
    url: "https://www.lotteryusa.com/maine/pick-3/",
    mainNumbers: 3,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "07:59 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_me",
  },
  {
    game_id: "pick4midday_me",
    state: "ME",
    displayName: "Pick 4 Midday",
    url: "https://www.lotteryusa.com/maine/pick-4-midday/",
    mainNumbers: 4,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "01:00 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_me",
  },
  {
    game_id: "pick4evening_me",
    state: "ME",
    displayName: "Pick 4 Evening",
    url: "https://www.lotteryusa.com/maine/pick-4/",
    mainNumbers: 4,
    hasExtraBall: false,
    supportsCashValue: false,
    drawTimeET: "07:59 PM",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    table: "results_me",
  },
];
